application: applicationname
version: 1
runtime: python27
api_version: 1
threadsafe: true


handlers:
- url: /static
  static_dir: static

- url: /task/clean
  script: tasks.app
  login: admin

- url: /.*
  script: views.app


libraries:
- name: PIL
  version: "1.1.7"
